apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: j8axrx6h5-python 
  janus-idp.io/tekton: j8axrx6h5-python
  backstage.io/kubernetes-id: j8axrx6h5-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j8axrx6h5-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml